### ISSUE TITLE
support for all commands?

### ISSUE THREAD

**Issue by immerhart** [ntex-rs/ntex-redis#9]
Hey, are there any plans to support "all" commands e.g. redis streams. Or is there some "raw" interface which can be used for missing commands?

**Comment by fafhrd91** [comment]
at the moment, not all commands are supported. I am not sure when I will have time for implementation but PRs are always welcomed

**Comment by estin** [comment]
@immerhart hi!

I have some experience and code to use ntex_rs with unimplemented commands and most cases it's not hard task for request-response comands

```rust
use ntex_redis::codec::{Request, Response};
use ntex_redis::errors::CommandError;
use ntex_redis::{cmd::Command, RedisConnector};
use std::convert::TryFrom;
use std::error::Error;

pub struct RawCommand(Request);

impl Command for RawCommand {
    type Output = Response;
    fn to_request(self) -> Request {
        self.0
    }
    fn to_output(val: Response) -> Result<Self::Output, CommandError> {
        Ok(val)
    }
}

#[ntex::main]
async fn main() -> Result<(), Box<dyn Error>> {
    env_logger::init();

    let redis = RedisConnector::new("127.0.0.1:6379").connect().await?;

    // XADD somestream 0-1 key value
    let request = Request::from_static("XADD")
        .add(Request::from_static("somestream"))
        .add(Request::from_static("0-1"))
        .add(Request::from_static("key"))
        .add(Request::from_static("value"));
    _ = redis.exec(RawCommand(request)).await?;

    // XLEN somestream
    let request = Request::from_static("XLEN").add(Request::from_static("somestream"));
    let response = redis.exec(RawCommand(request)).await?;
    let len = i64::try_from(response).unwrap();
    println!("len {len:?}");

    Ok(())
}
```

**Comment by immerhart** [comment]
> @immerhart hi!
> 
> I have some experience and code to use ntex_rs with unimplemented commands and most cases it's not hard task for request-response comands
> 
> ```rust
> use ntex_redis::codec::{Request, Response};
> use ntex_redis::errors::CommandError;
> use ntex_redis::{cmd::Command, RedisConnector};
> use std::convert::TryFrom;
> use std::error::Error;
> 
> pub struct RawCommand(Request);
> 
> impl Command for RawCommand {
>     type Output = Response;
>     fn to_request(self) -> Request {
>         self.0
>     }
>     fn to_output(val: Response) -> Result<Self::Output, CommandError> {
>         Ok(val)
>     }
> }
> 
> #[ntex::main]
> async fn main() -> Result<(), Box<dyn Error>> {
>     env_logger::init();
> 
>     let redis = RedisConnector::new("127.0.0.1:6379").connect().await?;
> 
>     // XADD somestream 0-1 key value
>     let request = Request::from_static("XADD")
>         .add(Request::from_static("somestream"))
>         .add(Request::from_static("0-1"))
>         .add(Request::from_static("key"))
>         .add(Request::from_static("value"));
>     _ = redis.exec(RawCommand(request)).await?;
> 
>     // XLEN somestream
>     let request = Request::from_static("XLEN").add(Request::from_static("somestream"));
>     let response = redis.exec(RawCommand(request)).await?;
>     let len = i64::try_from(response).unwrap();
>     println!("len {len:?}");
> 
>     Ok(())
> }
> ```

Thanks, will give it a try.
